os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py
    - python: 3.6
      env: TOXENV=py
    - python: 3.7
      env: TOXENV=py
    - python: 3.8-dev
      env: TOXENV=py
    - python: pypy
      env: TOXENV=py
    - python: pypy3
      env: TOXENV=py

install:
  - pip install tox
cache:
  - pip
script:
  - tox
